language: java

cache:
  directories:
    - ~/.m2

before_install:
  # Needed to publish sample report on github pages successfully
  - gem install public_suffix -v 3.0.3

matrix:
  - jdk: openjdk8
    env:
      - DESC="tests by openjdk8"
    script: mvn verify

  - jdk: oraclejdk11
    env:
      - DESC="tests by oraclejdk11"
    script:
      - mvn clean verify

  - jdk: openjdk11
    env:
      - DESC="tests by openjdk11"
    script:
      - mvn clean verify
